name: Create and publish a Docker image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:

  build-and-push:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Build and push Docker image
        env:
          GH_REGISTRY_USERNAME: ${{ github.actor }}
          GH_REGISTRY_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
          REGISTRY: ${{ env.REGISTRY }}
          IMAGE_NAME: ${{ github.repository }} # gh_user/gh_repo_name
        run: |
          echo REGISTRY: ${REGISTRY}
          echo GH_REGISTRY_USERNAME: ${GH_REGISTRY_USERNAME}
          echo IMAGE_NAME: ${IMAGE_NAME}
          echo ${GH_REGISTRY_TOKEN} | docker login ${REGISTRY} -u ${GH_REGISTRY_USERNAME} --password-stdin
          now=$(date --rfc-3339=seconds --utc)
          revision=${GITHUB_SHA:0:7}
          ref_name=${GITHUB_REF#refs/*/}
          docker build \
            --build-arg CREATED="${now}" --build-arg REVISION=${revision}  --build-arg REF_NAME=${ref_name} \
            -t ${REGISTRY}/${IMAGE_NAME}:latest .
          docker push ${REGISTRY}/${IMAGE_NAME}:latest:latest
